# Generated by Django 5.0.6 on 2024-07-09 06:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0002_consumers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consumers",
            new_name="Consume",
        ),
    ]
